### ISSUE TITLE
Better API for audio

### ISSUE THREAD

**Issue by tedsteen** [zeta0134/rusticnes-core#13]
Right now we have to wait for rusticnes to fill a buffer before we get to see any audiodata.

It would be nice to be able to read however many bytes are available at any given time. Exposing a consumer of the underlying ring buffer would be a nice way to expose the buffer.

**Comment by tedsteen** [comment]
Maybe you have grand plans for this API, but IMO this commit closes this issue :)
https://github.com/zeta0134/rusticnes-core/commit/2d3fa46341f4e6affa712bed66ac1750a51eb912

**Comment by zeta0134** [comment]
Oh, no that was the goal XD I may yet remove the old buffer approach, though I still want a limit for applications that ignore audio, so memory doesn't get out of hand.
