### ISSUE TITLE
Add BNROM mapper (34)

### ISSUE THREAD

**Issue by pinobatch** [zeta0134/rusticnes-core#7]
[BNROM](https://wiki.nesdev.com/w/index.php/BNROM) is a discrete board used for the games _Deadly Towers_, _Lizard_, and _Haunted: Halloween '85_. It is the same as AMROM (mapper 7) with conventional fixed H/V mirroring instead of switchable 1-screen mirroring. The BNTest ROM in [little things](https://github.com/pinobatch/little-things-nes/releases) produces "Unsupported iNES mapper: 34" unless the mapper 7 version is run.

**Comment by zeta0134** [comment]
This is addressed by https://github.com/zeta0134/rusticnes-core/commit/f9a587274b093013b24d3284e4fe467c74b8ee2c
