### ISSUE TITLE
Add Sunsoft FME-7 mapper (69)

### ISSUE THREAD

**Issue by pinobatch** [zeta0134/rusticnes-core#9]
[Sunsoft FME-7, 5A, and 5B](https://wiki.nesdev.com/w/index.php/Sunsoft_FME-7) is an ASIC mapper used in _Hebereke_/_Ufouria_, _Batman: Return of the Joker_, and _Gimmick!_. The fme7acktest, fme7ramtest, and vwfterm ROMs in [little things](https://github.com/pinobatch/little-things-nes/releases) produce "Unsupported iNES mapper: 69".

**Comment by zeta0134** [comment]
Closing this out. FME-7 and Sunsoft 5B audio has been implemented for a while now. Oops!
